"""Generate the taxonomy coverage matrix.

Reads:
  - tasks/*.yaml (every task spec)
  - verification/reports/**/*.yaml (every verification result)

Writes:
  - verification/coverage.md

A taxonomy_id is "covered" iff at least one task claims it AND the claim is
verified=true in the corresponding report.

Stub for WS-9. The schema it walks is in validator.md \u00a72 + \u00a77.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import yaml


# Full taxonomy ID set, kept in sync with validator.md §2.
DISTRACTOR_IDS = [
    "D.T.CAT", "D.T.SCH", "D.T.NAME", "D.T.NOC", "D.T.WCM",
    "D.T.TAG-", "D.T.TAG+", "D.T.SEM", "D.T.RUP",
    "D.N.DEP", "D.N.WQ", "D.N.BUG",
    "D.D.DEP", "D.D.WQ", "D.D.BUG",
    "D.NA.*",
]
ANCHOR_IDS = [
    "A.T.AUTH", "A.T.NOC", "A.T.NCAT", "A.T.NMD",
    "A.N.AUTH", "A.N.NA",
    "A.D.AUTH", "A.D.NA",
    "A.G.AUTH", "A.G.NA",
    "A.NA.CUI", "A.NA.JRH", "A.NA.TAG", "A.NA.LIN", "A.NA.USE", "A.NA.FRH",
]
ALL_IDS = DISTRACTOR_IDS + ANCHOR_IDS


def collect(tasks_dir: Path, reports_dir: Path) -> dict[str, dict]:
    coverage: dict[str, dict] = {tid: {"tasks": set(), "verified": 0, "unverified": 0} for tid in ALL_IDS}

    for task_path in sorted(tasks_dir.glob("T-*.yaml")):
        task = yaml.safe_load(task_path.read_text())
        task_id = task.get("id", task_path.stem)
        for claim in (task.get("distractors") or []) + (task.get("anchors") or []):
            tid = claim.get("taxonomy_id")
            if tid in coverage:
                coverage[tid]["tasks"].add(task_id)
                if claim.get("verified"):
                    coverage[tid]["verified"] += 1
                else:
                    coverage[tid]["unverified"] += 1
    return coverage


def render(coverage: dict[str, dict]) -> str:
    lines = [
        "# Taxonomy coverage matrix",
        "",
        "Generated by `tools/coverage_matrix.py`. Phase 2 cannot ship if any row has `verified = 0`.",
        "",
        "| taxonomy_id | covered_by_tasks | verified | unverified |",
        "| ----------- | ---------------- | -------- | ---------- |",
    ]
    for tid in ALL_IDS:
        c = coverage[tid]
        lines.append(
            f"| `{tid}` | "
            f"{', '.join(sorted(c['tasks'])) or '—'} | "
            f"{c['verified']} | "
            f"{c['unverified']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tasks-dir", default="tasks")
    parser.add_argument("--reports-dir", default="verification/reports")
    parser.add_argument("--out", default="verification/coverage.md")
    args = parser.parse_args()

    coverage = collect(Path(args.tasks_dir), Path(args.reports_dir))
    Path(args.out).write_text(render(coverage))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
